### PR TITLE
firewall module 0.1.0

### PR DESCRIPTION
**Pull request by cshea-msft**
Pushing new FIrewall module into the main branch.

### CODE REVIEW

**Comment by cshea-msft** [comment]
@Azure/avm-core-team-technical PR ready for review.

**Comment by prjelesi** [comment]
@cshea-msft us know when we can start with review

**Comment by cshea-msft** [comment]
@prjelesi ready for review

**Review by mbilalamjad — APPROVED** [review]
Thank you for the PR

**Pull request merged**
